<?php

namespace Tests\Feature\Http\Controllers\Mission;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Mission\Incomplete
 */
class IncompleteTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function invoke_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\User::class)->create();

        $response = $this->actingAs($user)->put(route('mission.incomplete', ['mission' => $mission]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(withWarning('Completion claim rejected'));

        // TODO: perform additional assertions
    }

    // test cases...
}
